### ISSUE TITLE
 Banner on rotate device

### ISSUE THREAD

**Issue by micik** [admob-google/admob-phonegap#1]
i used 
        admob.showBanner(admob.BannerSize.SMART_BANNER,admob.Position.BOTTOM_APP,admobParam);

all is well when the application booted, but when I rotate device banner has old size see Attach
![screenshot_2015-01-15-12-53-19](https://cloud.githubusercontent.com/assets/2856674/5756308/9b12b9b4-9cb6-11e4-9735-49fad985ead4.png)
![screenshot_2015-01-15-12-53-38](https://cloud.githubusercontent.com/assets/2856674/5756309/9b132444-9cb6-11e4-87ca-6c1a5ef17367.png)

please tell me how to fix it?

**Comment by admob-google** [comment]
smart banner size is managed by admob sdk auto.
